<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="INLN50940634A" name="TestNG.LE.OutboundDeliveries" tests="9" failures="0" timestamp="03 Jan 2019 03:47:04 GMT" time="0.034" errors="1">
  <testcase name="changeDelivery" time="0.002" classname="TestNG.LE.OutboundDeliveries"/>
  <testcase name="createDelivery" time="0.007" classname="TestNG.LE.OutboundDeliveries"/>
  <testcase name="methodUsingDataFromProvider" time="0.003" classname="TestNG.LE.OutboundDeliveries"/>
  <testcase name="postGoodsIssueDelivery" time="0.001" classname="TestNG.LE.OutboundDeliveries">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at TestNG.LE.OutboundDeliveries.postGoodsIssueDelivery(OutboundDeliveries.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- postGoodsIssueDelivery -->
  <testcase name="someFITestsThatDependonGroupLogistics" time="0.006" classname="TestNG.LE.OutboundDeliveries"/>
  <testcase name="displayDelivery" time="0.002" classname="TestNG.LE.OutboundDeliveries"/>
  <testcase name="methodUsingDataFromProvider" time="0.008" classname="TestNG.LE.OutboundDeliveries"/>
  <testcase name="methodUsingDataFromProvider" time="0.005" classname="TestNG.LE.OutboundDeliveries"/>
  <testcase name="billForDelivery" time="0.000" classname="TestNG.LE.OutboundDeliveries">
    <skipped/>
  </testcase> <!-- billForDelivery -->
</testsuite> <!-- TestNG.LE.OutboundDeliveries -->
